### ISSUE TITLE
How do I compile

### ISSUE THREAD

**Issue by Suspect-byte** [awawa-dev/HyperSPI#6]
Hello,

First of all thanks for creating this masterpiece. 
Second how do I compile the script. I am really new to arduino. I managed to install all the libararies, but I get all questions marks in the sketch after adding the libaries. I need to change the GPIO pins for data for my ESP32 because I don't have a GPIO 0.

Could you head me to the right direction.

Thanks in advance

**Comment by awawa-dev** [comment]
Thanks! Are you sure you don't have GPIO 0 on your board? Do you have a link to your model or could you take a detailed picture of your ESP32? I've never met a generic ESP2 board without that port available and in this case do you have VSPI interface? Without VSPI (or at least HSPI but I didn't test it) you won't be able to connect to your RPi.  

If you are starting your fun with the Arduino Studio then first make sure you set up your ESP32 environmental using one of the typical tutorial you can find one the internet. E.g https://randomnerdtutorials.com/installing-the-esp32-board-in-arduino-ide-windows-instructions/ Follow it, compile the test sketch, upload to ESP32 and watch the result. If everything is fine then return back to HyperSPI, install needed libraries, compile the sketch and connect to the serial output at 115200 speed. You should have some output.

**Comment by awawa-dev** [comment]
BTW GPIO0  is used only for SPI leds. I only see one case when you may need it: very high&stable SPI for LED strip which is not available for Rpi. Still, the RPI to ESP32 communication will be a bottleneck.

**Comment by Suspect-byte** [comment]
@awawa-dev Thanks for your response, I got the ESP32 Devkit CH9102X, CH340C and CP2102.

https://nl.aliexpress.com/item/1005001621773806.html?spm=a2g0o.order_list.0.0.21ef79d26MBwL3&gatewayAdapt=glo2nld

**Comment by awawa-dev** [comment]
In that offer all these boards have a GPIO0 and GPIO2. E.g. ```GPIO0``` can be marked as ```IO0``` or simply ```0```

**Comment by awawa-dev** [comment]
Edit: In 30 pin version I can't locate them. But either can't locate VSPI  interface so maybe ask the seller about schematic.

**Comment by Suspect-byte** [comment]
@awawa-dev I found a schematic http://www.electronica.com.py/wp-content/uploads/MODULO-ESP32-DEV-BOARD-30P-CON-WIFI-Y-BLUETOOTH-3.jpg I dont see a GPIO0 but I found a MOSI at GPIO23 and a MISO at GPIO19

**Comment by awawa-dev** [comment]
Migrated to platformio. Online-compiling manual: https://github.com/awawa-dev/HyperSPI/wiki
